language: python
python:
  - '2.7'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.2
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - flake8 . --max-line-length=120 --max-complexity=10 --exclude='env,migrations,*.egg'
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - coverage run --source='querybuilder' --branch --omit='querybuilder/migrations/*' setup.py test
  - coverage report --fail-under=100 --show-missing
