sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.7,<1.8"
    - DJANGO=">=1.8,<1.9"
install:
  - pip install -q coverage coveralls flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=92
after_success:
  coveralls
