sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.11
    - DJANGO=1.7.7
addons:
  postgresql: '9.3'
install:
  - pip install -q coverage coveralls flake8 Django==$DJANGO
before_script:
  - psql -c 'CREATE DATABASE querybuilder;' -U postgres
script:
  - flake8 ./querybuilder
  - coverage run setup.py test
  - coverage report --fail-under=92
after_success:
  coveralls
